-- 1. Users 테이블 생성 (Auth 연동)
create table public.users (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  avatar_url text,
  company text,
  job_title text,
  created_at timestamptz default now()
);

-- 2. Gatherings 테이블 생성 (Host ID 외래키 포함)
create table public.gatherings (
  id bigint generated by default as identity primary key,
  host_id uuid references public.users not null,
  title text not null,
  content text,
  location text not null,
  meet_at timestamptz not null,
  capacity int default 4,
  image_url text,
  category text,
  status text default 'recruiting',
  created_at timestamptz default now(),
  latitude float8,
  longitude float8
);

-- 3. Participations 테이블 생성 (참여 내역)
create table public.participations (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users not null,
  gathering_id bigint references public.gatherings on delete cascade not null,
  status text default 'joined',
  created_at timestamptz default now(),
  unique(user_id, gathering_id)
);

-- 4. RLS(보안) 활성화
alter table public.users enable row level security;
alter table public.gatherings enable row level security;
alter table public.participations enable row level security;

-- 5. 누구나 조회 가능 정책 (Policy)
create policy "Public profiles are viewable by everyone." on users for select using ( true );
create policy "Anyone can view gatherings." on gatherings for select using ( true );
create policy "Anyone can view participations." on participations for select using ( true );

-- 6. 로그인한 사용자만 쓰기 가능 정책
create policy "Users can update own profile." on users for update using ( auth.uid() = id );
-- [FIX] Allow INSERT for new users (sign up)
create policy "Enable insert for authenticated users only" on public.users for insert with check ( auth.uid() = id );

create policy "Authenticated users can create gatherings." on gatherings for insert with check ( auth.role() = 'authenticated' );
create policy "Authenticated users can join." on participations for insert with check ( auth.role() = 'authenticated' );

-- 7. [TRIGGER] Automatically create public.users profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name, avatar_url)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'name', 
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
