-- 1. 유저 테이블에 매너 온도 추가 (기본 36.5)
ALTER TABLE users ADD COLUMN IF NOT EXISTS manner_score FLOAT DEFAULT 36.5;

-- 2. 유저 리뷰 테이블 생성 (중복 평가 방지)
CREATE TABLE IF NOT EXISTS user_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reviewer_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  reviewee_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  gathering_id BIGINT REFERENCES gatherings(id) ON DELETE CASCADE,
  score INT NOT NULL CHECK (score IN (1, -1)), -- 1: 좋아요, -1: 별로예요
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(reviewer_id, reviewee_id, gathering_id)
);

-- 3. 리뷰 추가 시 manner_score 자동 업데이트 트리거
CREATE OR REPLACE FUNCTION update_manner_score()
RETURNS TRIGGER AS $$
BEGIN
  -- 좋아요(+1) -> +0.5점, 싫어요(-1) -> -0.5점
  UPDATE users
  SET manner_score = manner_score + (NEW.score * 0.5)
  WHERE id = NEW.reviewee_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_review_created
AFTER INSERT ON user_reviews
FOR EACH ROW
EXECUTE FUNCTION update_manner_score();
