-- Create chat_messages table
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  gathering_id bigint not null references public.gatherings(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.chat_messages enable row level security;

-- Policy for viewing messages
-- Users can view messages if they are the host OR a joined participant
create policy "Users can view messages of gatherings they belong to"
  on public.chat_messages for select
  using (
    -- Is Host
    auth.uid() in (
      select host_id from public.gatherings where id = gathering_id
    )
    OR
    -- Is Joined Participant
    auth.uid() in (
      select user_id from public.participations 
      where gathering_id = chat_messages.gathering_id 
      and status = 'joined' -- Only joined members
    )
  );

-- Policy for inserting messages
-- Users can insert messages if they are the host OR a joined participant
create policy "Users can send messages to gatherings they belong to"
  on public.chat_messages for insert
  with check (
    -- Is Host
    auth.uid() in (
      select host_id from public.gatherings where id = gathering_id
    )
    OR
    -- Is Joined Participant
    auth.uid() in (
      select user_id from public.participations 
      where gathering_id = chat_messages.gathering_id 
      and status = 'joined'
    )
  );

-- Add indexes for performance
create index if not exists chat_messages_gathering_id_idx on public.chat_messages(gathering_id);
create index if not exists chat_messages_created_at_idx on public.chat_messages(created_at);
