-- 1. Create gathering_applications table
create table public.gathering_applications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users not null,
  gathering_id bigint references public.gatherings on delete cascade not null,
  created_at timestamptz default now(),
  message text,
  unique(user_id, gathering_id) -- Prevent duplicate applications
);

-- 2. Enable RLS
alter table public.gathering_applications enable row level security;

-- 3. Policies
-- Users can view their own applications
create policy "Users can view own applications" on gathering_applications
  for select using (auth.uid() = user_id);

-- Hosts can view applications for their gatherings
create policy "Hosts can view applications for their gatherings" on gathering_applications
  for select using (
    exists (
      select 1 from public.gatherings
      where id = gathering_applications.gathering_id
      and host_id = auth.uid()
    )
  );

-- Authenticated users can create applications
create policy "Authenticated users can apply" on gathering_applications
  for insert with check (auth.role() = 'authenticated');

-- Users can delete their own applications (cancel)
create policy "Users can cancel own application" on gathering_applications
  for delete using (auth.uid() = user_id);

-- Hosts can delete applications (reject/approve cleanup)
create policy "Hosts can process applications" on gathering_applications
  for delete using (
    exists (
      select 1 from public.gatherings
      where id = gathering_applications.gathering_id
      and host_id = auth.uid()
    )
  );
