-- 알림 테이블 (Notifications Table)
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL, -- 'APPROVAL', 'REJECTION', 'NEW_COMMENT'
  content TEXT NOT NULL,
  link_url TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security) 설정
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- 사용자는 본인의 알림만 조회 가능
CREATE POLICY "Users can view own notifications" 
ON public.notifications FOR SELECT 
USING (auth.uid() = user_id);

-- 시스템(서버 롤)에서 알림 삽입 가능 (간단한 구현을 위해 일단 authenticated도 허용, 필요시 제어)
CREATE POLICY "Users can insert notifications" 
ON public.notifications FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

-- 사용자는 본인의 알림만 수정(읽음 처리) 가능
CREATE POLICY "Users can update own notifications" 
ON public.notifications FOR UPDATE 
USING (auth.uid() = user_id);

-- Realtime 연동을 위해 publication에 테이블 추가
-- 만약 이미 supabase_realtime publication이 있다면 아래 명령어 실행
ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
