-- 1. Comments Table
create table public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users not null,
  gathering_id bigint references public.gatherings on delete cascade not null,
  content text not null,
  created_at timestamptz default now()
);

-- 2. Likes Table
create table public.likes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users not null,
  gathering_id bigint references public.gatherings on delete cascade not null,
  created_at timestamptz default now(),
  unique(user_id, gathering_id) -- Prevent duplicate likes
);

-- 3. Enable RLS
alter table public.comments enable row level security;
alter table public.likes enable row level security;

-- 4. Policies for Comments
-- Anyone can view comments
create policy "Public comments are viewable by everyone." on comments for select using ( true );
-- Authenticated users can create comments
create policy "Authenticated users can create comments." on comments for insert with check ( auth.role() = 'authenticated' );
-- Users can delete their own comments
create policy "Users can delete own comments." on comments for delete using ( auth.uid() = user_id );

-- 5. Policies for Likes
-- Anyone can view likes (to count them)
create policy "Public likes are viewable by everyone." on likes for select using ( true );
-- Authenticated users can toggle likes (insert/delete)
create policy "Authenticated users can create likes." on likes for insert with check ( auth.role() = 'authenticated' );
create policy "Users can delete own likes." on likes for delete using ( auth.uid() = user_id );
